### ISSUE TITLE
Do you have plans to release training code?

### ISSUE THREAD

**Issue by YuyangYin** [lixirui142/VidToMe#1]
Congratulations on being accepted by CVPR 2024! Do you have plans to release training code?

**Comment by lixirui142** [comment]
Hi Yin,
Our method is a zero-shot video editing method without the need of training. We have released the code here:&nbsp;https://github.com/lixirui142/VidToMe.


Best,
Xirui Li



zzz
***@***.***







                       
Original Email
                       
                     

Sender:"YuyangYin"< ***@***.*** &gt;;

Sent Time:2024/2/28 11:22

To:"lixirui142/VidToMe"< ***@***.*** &gt;;

Cc recipient:"Subscribed"< ***@***.*** &gt;;

Subject:[lixirui142/VidToMe] Do you have plans to release training code?(Issue #1)




 
Congratulations on being accepted by CVPR 2024! Do you have plans to release training code?

**Comment by lixirui142** [comment]
Thanks! VidToMe is a zero-shot video editing method without the need for training. We use existing pretrained SD models for frame generation.

**Comment by YuyangYin** [comment]
Oh, sorry. Thanks for your reply.
