### ISSUE TITLE
How to transform video into animation(video - video to video)?

### ISSUE THREAD

**Issue by zhanghongyong123456** [lixirui142/VidToMe#2]
1. about   video2animation, like   domoAI(https://domoai.app/)   and   Goenhance(https://www.goenhance.ai/) ,Is the implementation the same as this project implementation, or is there another implementation, like AnimateDIff?
2. Do you have a video2video implementation project recommendation? I don't know much about this direction   
very thankful!

**Comment by lixirui142** [comment]
1. VidToMe can do similar things like video style editing. But their results are more likely obtained by a finetuned model, such as AnimateDiff.
2. video2video is exactly what VidToMe tries to do. You can also check [TokenFlow](https://github.com/omerbt/TokenFlow), [Rerender-A-Video](https://github.com/williamyang1991/Rerender_A_Video)

**Comment by zhanghongyong123456** [comment]
> 1. VidToMe can do similar things like video style editing. But their results are more likely obtained by a finetuned model, such as AnimateDiff.
> 2. video2video is exactly what VidToMe tries to do. You can also check [TokenFlow](https://github.com/omerbt/TokenFlow), [Rerender-A-Video](https://github.com/williamyang1991/Rerender_A_Video)

yes,i  test   this  project(https://github.com/omerbt/TokenFlow/issues/12),It is difficult to achieve video consistency, and both projects are difficult to adjust consistency and have a lot of randomness

**Comment by lixirui142** [comment]
> yes,i test this project([omerbt/TokenFlow#12](https://github.com/omerbt/TokenFlow/issues/12) is difficult to achieve video consistency, and both projects are difficult to adjust consistency and have a lot of randomness

The video you present is a reconstruction result in preprocessing, just for reference and no temporal consistency is enforced. Run "python run_tokenflow_pnp.py" to get the edit result, as stated in [README](https://github.com/omerbt/TokenFlow/blob/master/README.md).

**Comment by zhanghongyong123456** [comment]
> The video you present is a reconstruction result in preprocessing, just for reference and no temporal consistency is enforced. Run "python run_tokenflow_pnp.py" to get the edit result, as stated in [README](https://github.com/omerbt/TokenFlow/blob/master/README.md).

1. Thank you for your answer, I will test again,  
2.  I feel domoAI (https://domoai.app/) and Goenhance (https://www.goenhance.ai/), the effect is very stable, is there a similar implementation projects

**Comment by lixirui142** [comment]
I have no idea. They should have combined several existing techs.
